### ISSUE TITLE
Boiled noodles 

### ISSUE THREAD

**Issue by TH3xACE** [keethesh/keethesh#1]
Mine apollo ou mine mona ça ? :)

**Comment by keethesh** [comment]
Apollo > Mona

**Comment by keethesh** [comment]
Pourquoi cette question? 😂

**Comment by TH3xACE** [comment]
Juste pour savoir à quoi tu faisais allusion quand tu disais “boiled noodles”…. enfaite j’ai vu que tu avais mis un star sur mon projet SUDO_KILLER et ça m’a fait plaisir de voir un mauricien ;)

**Comment by keethesh** [comment]
De meme! En passant, j'ai tres envie d'etudier dans le domaine de la cybersecurite, et je vois que tu travailles dans ce secteur. Ca te derange qu'on en discute sur Twitter?

**Comment by TH3xACE** [comment]
Discord > TH3xACE#0453

**Comment by keethesh** [comment]
Ok :)
